/************************************************************************************************

	Project:			CHEOPS On-Board Software
	Target System:		Leon3-Processor
	Language:			C

	Author:				B.Ulmer(IBU)
	Label:

	Header Information automatically generated by Subversion

	$Rev: 2275 $
	$Author: ulmer $
	$Date: 2017-08-08 13:32:33 +0200 (Di, 08 Aug 2017) $
	$Id: register.h 2275 2017-08-08 11:32:33Z ulmer $
	$HeadURL: https://svn.dlr.de/CHEOPS/03-SES_ENGINEERING/07-Software/Development/APS/trunk/src/Include/register.h $

*************************************************************************************************/
 
#ifndef __REGISTER_H_
#define __REGISTER_H_

#include "config.h"
#include "address.h"

// General Macros
#ifndef GCC_ASM
	#define _MEMIO_BYTE(mem_addr) (*(volatile unsigned char*)(mem_addr))
	#define _MEMIO_WORD(mem_addr) (*(volatile unsigned int*)(mem_addr))
#else
	#define _MEMIO_BYTE(mem_addr) (mem_addr)
	#define _MEMIO_WORD(mem_addr) (mem_addr)
#endif

#define _GET_REG_VAL(reg, mask, bit)		((reg & mask)>>bit)
#define _SET_REG_VAL(val, reg, mask, bit)	(reg = (reg&~mask)|((val<<bit)&mask))
#define _SET_REG_BIT(reg, mask)				(reg |= mask)
#define _CLEAR_REG_BIT(reg, mask)			(reg &= ~mask)

#define _APB_MEM8 (mem_addr) _MEMIO_BYTE(AHB_ADDR_APBCTRL + mem_addr)  // + 4)
#define _APB_MEM32(mem_addr) _MEMIO_WORD(AHB_ADDR_APBCTRL + mem_addr)
#define _APB_MEM32_HIGH(mem_addr) _MEMIO_WORD(AHB_ADDR_APBCTRL_HIGH + mem_addr)

/************************************* MCTRL ****************************************************/
// MCTRL
#define MCTRL_MCFG1_REG								_APB_MEM32(ADDR_MCTRL + 0x00)
#define MCTRL_MCFG2_REG								_APB_MEM32(ADDR_MCTRL + 0x04)
#define MCTRL_MCFG3_REG								_APB_MEM32(ADDR_MCTRL + 0x08)

/************************************* UART *****************************************************/
// UART1 Register
#define UART_DATA_REG								_APB_MEM32(ADDR_APBUART + 0x0)
#define UART_STATUS_REG								_APB_MEM32(ADDR_APBUART + 0x4)
#define UART_CTRL_REG								_APB_MEM32(ADDR_APBUART + 0x8)
#define UART_SCALER_REG								_APB_MEM32(ADDR_APBUART + 0xC)

/************************************* IRQMP ****************************************************/
// IRQMP
#define IRQMP_LEVEL_REG								_APB_MEM32(ADDR_IRQMP + 0x00)
#define IRQMP_PENDING_REG							_APB_MEM32(ADDR_IRQMP + 0x04)
#define IRQMP_FORCE_REG								_APB_MEM32(ADDR_IRQMP + 0x08)
#define IRQMP_CLEAR_REG								_APB_MEM32(ADDR_IRQMP + 0x0C)
#define IRQMP_MASK_REG								_APB_MEM32(ADDR_IRQMP + 0x40)

/************************************* GPTIMER **************************************************/
// GPTIMER Register
#define GPTIMER_SCALER_REG							_APB_MEM32(ADDR_GPTIMER + 0x00)
#define GPTIMER_SCALER_RELOAD_REG					_APB_MEM32(ADDR_GPTIMER + 0x04)
#define GPTIMER_CONFIG_REG							_APB_MEM32(ADDR_GPTIMER + 0x08)
#define GPTIMER1_COUNTER_REG						_APB_MEM32(ADDR_GPTIMER + 0x10)
#define GPTIMER1_COUNTER_RELOAD_REG					_APB_MEM32(ADDR_GPTIMER + 0x14)
#define GPTIMER1_CTRL_REG							_APB_MEM32(ADDR_GPTIMER + 0x18)
#define GPTIMER2_COUNTER_REG						_APB_MEM32(ADDR_GPTIMER + 0x20)
#define GPTIMER2_COUNTER_RELOAD_REG					_APB_MEM32(ADDR_GPTIMER + 0x24)
#define GPTIMER2_CTRL_REG							_APB_MEM32(ADDR_GPTIMER + 0x28)

/************************************* GRSPW ****************************************************/
// GRSPW Register
#define GRSPW_CTRL_REG								_APB_MEM32_HIGH(ADDR_GRSPW + 0x00)
#define GRSPW_STAT_REG								_APB_MEM32_HIGH(ADDR_GRSPW + 0x04)
#define GRSPW_NODE_ADDR_REG							_APB_MEM32_HIGH(ADDR_GRSPW + 0x08)
#define GRSPW_CLOCK_DIV_REG							_APB_MEM32_HIGH(ADDR_GRSPW + 0x0C)
#define GRSPW_DEST_KEY_REG							_APB_MEM32_HIGH(ADDR_GRSPW + 0x10)
#define GRSPW_TIME_REG								_APB_MEM32_HIGH(ADDR_GRSPW + 0x14)
#define GRSPW1_TIMER_DISCNT_REG						_APB_MEM32_HIGH(ADDR_GRSPW + 0x18)
#define GRSPW_DMA1_CTRL_STAT_REG					_APB_MEM32_HIGH(ADDR_GRSPW + 0x20)
#define GRSPW_DMA1_RX_MAX_LEN_REG					_APB_MEM32_HIGH(ADDR_GRSPW + 0x24)
#define GRSPW_DMA1_TX_DESCR_ADDR_REG				_APB_MEM32_HIGH(ADDR_GRSPW + 0x28)
#define GRSPW_DMA1_RX_DESCR_ADDR_REG				_APB_MEM32_HIGH(ADDR_GRSPW + 0x2C)
#define GRSPW2_DMA1_ADDR_REG						_APB_MEM32_HIGH(ADDR_GRSPW + 0x30)

#endif

