/************************************************************************************************

	Project:			CHEOPS On-Board Software
	Target System:		Leon3-Processor
	Language:			C

	Author:				B.Ulmer(IBU)
	Label: 				MER-IBU-SC-717

	Template for Header Information automatically generated by Subversion

	$Rev: 2612 $
	$Author: ulmer $
	$Date: 2018-03-12 00:20:51 +0100 (Mo, 12 Mrz 2018) $
	$Id: drv_wtdg.h 2612 2018-03-11 23:20:51Z ulmer $
	$HeadURL: https://svn.dlr.de/CHEOPS/03-SES_ENGINEERING/07-Software/Development/APS/branches/2.3/src/Include/drv_wtdg.h $

*************************************************************************************************/

#ifndef __WTD_DRV_H_
#define __WTD_DRV_H_

#ifndef GCC_ASM
	#include <stdio.h>
#endif

#include "register.h"

#ifndef GCC_ASM
//	#include "error.h"
//	#include "type.h"
#endif

// Watchdog Status and Control Bit Definition
#define WDG_EN_BIT									0
#define WDG_INT_EN_BIT								1
#define WDG_RESET_BIT								2
#define WDG_INT_STAT_BIT							3
#define WDG_CODE_LSB								16

// Watchdog Status and Control Bit Mask
#define WDG_EN										(1<<WDG_EN_BIT)
#define WDG_INT_EN									(1<<WDG_INT_EN_BIT)
#define WDG_RESET									(1<<WDG_RESET_BIT)
#define WDG_INT_STAT								(1<<WDG_INT_STAT_BIT)
#define WDG_CODE									(0xFFFF<<WDG_CODE_LSB)

// Watchdog Retrigger Value
#define	WDG_RETRIGGER_VALUE							0x51F988E0
#define	WDG_CODE_SIG								(0xD95A<<WDG_CODE_LSB)

// Watchdog Macros
#define _WDG_RETRIGGER()							WDG_TRIGGER_REG=WDG_RETRIGGER_VALUE
#define _SET_WDG_ICU_RESET()						(WDG_CONTROL_REG |= (WDG_CODE_SIG + WDG_RESET))
#define _SET_WDG_ENABLE()							(WDG_CONTROL_REG |= (WDG_CODE_SIG + WDG_EN))
#define _SET_WDG_DISABLE()							(WDG_CONTROL_REG  = (WDG_CODE_SIG +(WDG_CONTROL_REG & ~WDG_EN)))
#define _SET_WDG_INT_ENABLE()						(WDG_CONTROL_REG |= (WDG_CODE_SIG + WDG_INT_EN))
#define _SET_WDG_INT_DISABLE()						(WDG_CONTROL_REG  = (WDG_CODE_SIG + (WDG_STATUS_CTL_REG & ~WDG_INT_EN)))
#define _GET_WDG_INT_STATUS()						(_GET_REG_VAL(WDG_CONTROL_REG, WDG_INT_STAT, WDG_INT_STAT_BIT))
#define _GET_WDG_ENABLE()							(_GET_REG_VAL(WDG_CONTROL_REG, WDG_EN, WDG_EN_BIT))

#ifndef GCC_ASM
// Watchdog Functions
extern void vWDG_CfgSetupDefault(void);
extern uint32_t ui32WDG_CfgUpdateCSV(void);
extern void vWDG_CfgExportCSV(FILE *cfg);
extern void vWDG_HWLog(char* path);
extern void vWDG_CfgLog(char* path);
//extern Item_t* pxWDG_CfgGetItem(const char* cName);
//extern Func_Error_t eWDG_CfgSet(const char*	cName, void* data);
//extern Func_Error_t eWDG_CfgGet(const char*	cName, void* data);
extern void vWDG_Init(void);
extern void isrhandler_watchdog(void);
#endif

#endif /*WATCHDOG_H_*/
