/************************************************************************************************

	Project:			CHEOPS On-Board Software
	Target System:		Leon3-Processor
	Language:			C

	Author:				B.Ulmer(IBU)
	Label:

	Header Information automatically generated by Subversion

	$Rev: 2134 $
	$Author: ulmer $
	$Date: 2017-06-01 18:20:48 +0200 (Do, 01 Jun 2017) $
	$Id: address.h 2134 2017-06-01 16:20:48Z ulmer $
	$HeadURL: https://svn.dlr.de/CHEOPS/03-SES_ENGINEERING/07-Software/Development/APS/trunk/src/Include/address.h $

*************************************************************************************************/
 
#ifndef __ADDRESS_H_
#define __ADDRESS_H_

#define AHB_ADDR_PROM			0x00000000			/* PROM */
#define AHB_PROM_SIZE			0x00008000			/* 32kB */

#define AHB_ADDR_EEPROM			0x20000000			/* EEPROM */
#define AHB_EEPROM_SIZE			0x00200000			/*  2MB */

#define MAP_ADDR_VRAM			0x20200000			/* Virtueller Address Range of the EEPROM cache (somewhere in RAM) */
#define MAP_VRAM_SIZE			AHB_EEPROM_SIZE		/*  2MB */

#define MAP_ADDR_TRAM			0x21000000			/* Virtueller Address Range of the Timing scripts (somewhere in RAM) */
#define MAP_TRAM_SIZE			0x00010000			/*  64kByte */

#define AHB_ADDR_SDRAM			0x40000000			/* SDRAM */
#define AHB_SDRAM_SIZE			0x04000000			/*  128MB */

#define AHB_ADDR_INTERNAL_RAM	0x38000000			/*  software reset resistant RAM */
#define AHB_INTERNAL_RAM_SIZE	0x00000400			/*  1kB */

#define AHB_ADDR_APBCTRL		0x80000000			/* APB Bridge */
#define AHB_APBCTRL_SIZE		0x00100000

#define AHB_ADDR_DSU			0x90000000
#define AHB_ADDR_DSU_SIZE		0x10000000

													/* APB */
#define ADDR_MCTRL				0x0000
#define ADDR_APBUART			0x0100
#define ADDR_IRQMP				0x0200
#define ADDR_GPTIMER			0x0300
#define ADDR_HKADC				0x0400
#define ADDR_MIF				0x0500
#define	ADDR_DMA				0x0600
#define ADDR_AHBUART_DBG		0x0700
#define ADDR_FDI				0x0800
#define ADDR_FCI				0x0900
#define ADDR_GRSPW				0x0A00
#define ADDR_AHBSTAT			0x0D00
#define ADDR_FTAHBRAM			0x0E00
#define ADDR_ETHERNET			0x0F00

#define PBS_START_ADDR			0x47800000
#define SDRAM_EEPROM_CACHE_ADDR	0x44000000

#endif
