/************************************************************************************************

	Project:			CHEOPS On-Board Software
	Target System:		Leon3-Processor
	Language:			C

	Author:				B.Ulmer(IBU)
	Label:

	Header Information automatically generated by Subversion

	$Rev: 2275 $
	$Author: ulmer $
	$Date: 2017-08-08 13:32:33 +0200 (Di, 08 Aug 2017) $
	$Id: register.h 2275 2017-08-08 11:32:33Z ulmer $
	$HeadURL: https://svn.dlr.de/CHEOPS/03-SES_ENGINEERING/07-Software/Development/APS/trunk/src/Include/register.h $

*************************************************************************************************/
 
#ifndef __REGISTER_H_
#define __REGISTER_H_

//#include "config.h"
#include "address.h"

// General Macros
#ifndef GCC_ASM
	#define _MEMIO_BYTE(mem_addr) (*(volatile unsigned char*)(mem_addr))
	#define _MEMIO_WORD(mem_addr) (*(volatile unsigned int*)(mem_addr))
#else
	#define _MEMIO_BYTE(mem_addr) (mem_addr)
	#define _MEMIO_WORD(mem_addr) (mem_addr)
#endif

#define _GET_REG_VAL(reg, mask, bit)		((reg & mask)>>bit)
#define _SET_REG_VAL(val, reg, mask, bit)	(reg = (reg&~mask)|((val<<bit)&mask))
#define _SET_REG_BIT(reg, mask)				(reg |= mask)
#define _CLEAR_REG_BIT(reg, mask)			(reg &= ~mask)

#define _APB_MEM8 (mem_addr) _MEMIO_BYTE(AHB_ADDR_APBCTRL + mem_addr)  // + 4)
#define _APB_MEM32(mem_addr) _MEMIO_WORD(AHB_ADDR_APBCTRL + mem_addr)

/************************************* MCTRL ****************************************************/
// MCTRL
#define MCTRL_MCFG1_REG								_APB_MEM32(ADDR_MCTRL + 0x00)
#define MCTRL_MCFG2_REG								_APB_MEM32(ADDR_MCTRL + 0x04)
#define MCTRL_MCFG3_REG								_APB_MEM32(ADDR_MCTRL + 0x08)

/************************************* UART *****************************************************/
// UART1 Register
#define UART_DATA_REG								_APB_MEM32(ADDR_APBUART + 0x0)
#define UART_STATUS_REG								_APB_MEM32(ADDR_APBUART + 0x4)
#define UART_CTRL_REG								_APB_MEM32(ADDR_APBUART + 0x8)
#define UART_SCALER_REG								_APB_MEM32(ADDR_APBUART + 0xC)

/************************************* IRQMP ****************************************************/
// IRQMP
#define IRQMP_LEVEL_REG								_APB_MEM32(ADDR_IRQMP + 0x00)
#define IRQMP_PENDING_REG							_APB_MEM32(ADDR_IRQMP + 0x04)
#define IRQMP_FORCE_REG								_APB_MEM32(ADDR_IRQMP + 0x08)
#define IRQMP_CLEAR_REG								_APB_MEM32(ADDR_IRQMP + 0x0C)
#define IRQMP_MASK_REG								_APB_MEM32(ADDR_IRQMP + 0x40)

/************************************* GPTIMER **************************************************/
// GPTIMER Register
#define GPTIMER_SCALER_REG							_APB_MEM32(ADDR_GPTIMER + 0x00)
#define GPTIMER_SCALER_RELOAD_REG					_APB_MEM32(ADDR_GPTIMER + 0x04)
#define GPTIMER_CONFIG_REG							_APB_MEM32(ADDR_GPTIMER + 0x08)
#define GPTIMER1_COUNTER_REG						_APB_MEM32(ADDR_GPTIMER + 0x10)
#define GPTIMER1_COUNTER_RELOAD_REG					_APB_MEM32(ADDR_GPTIMER + 0x14)
#define GPTIMER1_CTRL_REG							_APB_MEM32(ADDR_GPTIMER + 0x18)
#define GPTIMER2_COUNTER_REG						_APB_MEM32(ADDR_GPTIMER + 0x20)
#define GPTIMER2_COUNTER_RELOAD_REG					_APB_MEM32(ADDR_GPTIMER + 0x24)
#define GPTIMER2_CTRL_REG							_APB_MEM32(ADDR_GPTIMER + 0x28)

/************************************* GRSPW ****************************************************/
// GRSPW Register
#define GRSPW_CTRL_REG								_APB_MEM32(ADDR_GRSPW + 0x00)
#define GRSPW_STAT_REG								_APB_MEM32(ADDR_GRSPW + 0x04)
#define GRSPW_NODE_ADDR_REG							_APB_MEM32(ADDR_GRSPW + 0x08)
#define GRSPW_CLOCK_DIV_REG							_APB_MEM32(ADDR_GRSPW + 0x0C)
#define GRSPW_DEST_KEY_REG							_APB_MEM32(ADDR_GRSPW + 0x10)
#define GRSPW_TIME_REG								_APB_MEM32(ADDR_GRSPW + 0x14)
#define GRSPW1_TIMER_DISCNT_REG						_APB_MEM32(ADDR_GRSPW + 0x18)
#define GRSPW_DMA1_CTRL_STAT_REG					_APB_MEM32(ADDR_GRSPW + 0x20)
#define GRSPW_DMA1_RX_MAX_LEN_REG					_APB_MEM32(ADDR_GRSPW + 0x24)
#define GRSPW_DMA1_TX_DESCR_ADDR_REG				_APB_MEM32(ADDR_GRSPW + 0x28)
#define GRSPW_DMA1_RX_DESCR_ADDR_REG				_APB_MEM32(ADDR_GRSPW + 0x2C)
#define GRSPW2_DMA1_ADDR_REG						_APB_MEM32(ADDR_GRSPW + 0x30)

/************************************* AHBSTAT **************************************************/
// AHB
#define AHB_STATUS_REG								_APB_MEM32(ADDR_AHBSTAT + 0x00)
#define AHB_FAILING_ADDR_REG						_APB_MEM32(ADDR_AHBSTAT + 0x04)

/************************************* MIF *******************************************************/
#define WDG_CONTROL_REG								_APB_MEM32(ADDR_MIF + 0x00)
#define WDG_TRIGGER_REG								_APB_MEM32(ADDR_MIF + 0x04)
#define WDG_RELOAD_REG								_APB_MEM32(ADDR_MIF + 0x08)
#define WDG_TIMER_REG								_APB_MEM32(ADDR_MIF + 0x0C)
#define PWR_GLOBAL_VERSION_REG						_APB_MEM32(ADDR_MIF + 0x10)
#define PWR_ICU_ID_REG								_APB_MEM32(ADDR_MIF + 0x14)
#define PWR_CONTROL_REG								_APB_MEM32(ADDR_MIF + 0x20)
#define PWR_STATUS_REG								_APB_MEM32(ADDR_MIF + 0x24)
#define PWR_UNLOCK_REG								_APB_MEM32(ADDR_MIF + 0x28)
#define PWR_HEATER_SELECT_REG						_APB_MEM32(ADDR_MIF + 0x2C)
#define PWR_HEATER_PWM_REG							_APB_MEM32(ADDR_MIF + 0x30)
#define TIA_CONTROL_REG								_APB_MEM32(ADDR_MIF + 0x3C)
#define WDG_VERSION_REG								_APB_MEM32(ADDR_MIF + 0xFC)

/***************************************** HK ***************************************************/
// ICU HK Register
#define HK_CONTROL_REG							_APB_MEM32(ADDR_HKADC + 0x00)
#define HK_STATUS_REG							_APB_MEM32(ADDR_HKADC + 0x04)
#define HK_ADC0_DATA00_REG						_APB_MEM32(ADDR_HKADC + 0x10)
#define HK_ADC0_DATA01_REG						_APB_MEM32(ADDR_HKADC + 0x14)
#define HK_ADC0_DATA02_REG						_APB_MEM32(ADDR_HKADC + 0x18)
#define HK_ADC0_DATA03_REG						_APB_MEM32(ADDR_HKADC + 0x1C)
#define HK_ADC0_DATA04_REG						_APB_MEM32(ADDR_HKADC + 0x20)
#define HK_ADC0_DATA05_REG						_APB_MEM32(ADDR_HKADC + 0x24)
#define HK_ADC0_DATA06_REG						_APB_MEM32(ADDR_HKADC + 0x28)
#define HK_ADC0_DATA07_REG						_APB_MEM32(ADDR_HKADC + 0x2C)
#define HK_ADC0_DATA08_REG						_APB_MEM32(ADDR_HKADC + 0x30)
#define HK_ADC0_DATA09_REG						_APB_MEM32(ADDR_HKADC + 0x34)
#define HK_ADC0_DATA10_REG						_APB_MEM32(ADDR_HKADC + 0x38)
#define HK_ADC0_DATA11_REG						_APB_MEM32(ADDR_HKADC + 0x3C)
#define HK_ADC0_DATA12_REG						_APB_MEM32(ADDR_HKADC + 0x40)
#define HK_ADC0_DATA13_REG						_APB_MEM32(ADDR_HKADC + 0x44)
#define HK_ADC0_DATA14_REG						_APB_MEM32(ADDR_HKADC + 0x48)
#define HK_ADC0_DATA15_REG						_APB_MEM32(ADDR_HKADC + 0x4C)
#define HK_ADC0_COMMAND_REG						_APB_MEM32(ADDR_HKADC + 0x50)
#define HK_ADC0_CONVTIME_REG					_APB_MEM32(ADDR_HKADC + 0x54)
#define HK_ADC0_SEQLEN_REG						_APB_MEM32(ADDR_HKADC + 0x5C)
#define HK_ADC0_SEQUENCE0_REG					_APB_MEM32(ADDR_HKADC + 0x60)
#define HK_ADC0_SEQUENCE1_REG					_APB_MEM32(ADDR_HKADC + 0x64)
#define HK_ADC0_SEQUENCE2_REG					_APB_MEM32(ADDR_HKADC + 0x68)
#define HK_ADC0_SEQUENCE3_REG					_APB_MEM32(ADDR_HKADC + 0x6C)
#define HK_ADC0_SGLMODE_REG						_APB_MEM32(ADDR_HKADC + 0x70)
#define HK_HK_VERSION_REG						_APB_MEM32(ADDR_HKADC + 0xFC)

/************************************* FEE Control *********************************************/
#define FCI_POWER_REG							_APB_MEM32(ADDR_FCI + 0x00)
#define FCI_LATCHUP_REG							_APB_MEM32(ADDR_FCI + 0x04)
#define FCI_STATUS_REG							_APB_MEM32(ADDR_FCI + 0x08)
#define FCI_FEE_VERSION_REG						_APB_MEM32(ADDR_FCI + 0x0C)
#define FCI_CCD_CONTROL_REG						_APB_MEM32(ADDR_FCI + 0x10)
#define FCI_CCD_STATUS_REG						_APB_MEM32(ADDR_FCI + 0x14)
#define FCI_DAC_VRD_REG							_APB_MEM32(ADDR_FCI + 0x24)
#define FCI_DAC_VOD_REG							_APB_MEM32(ADDR_FCI + 0x28)
#define FCI_DAC_VSS_REG							_APB_MEM32(ADDR_FCI + 0x2C)
#define FCI_HK0_CONFIG_REG						_APB_MEM32(ADDR_FCI + 0x30)
#define FCI_HK1_CONFIG_REG						_APB_MEM32(ADDR_FCI + 0x38)
#define FCI_HK0_DATA12D_REG						_APB_MEM32(ADDR_FCI + 0x3C)
#define FCI_HK0_DATA00D_REG						_APB_MEM32(ADDR_FCI + 0x40)
#define FCI_HK0_DATA02D_REG						_APB_MEM32(ADDR_FCI + 0x44)
#define FCI_HK0_DATA04D_REG						_APB_MEM32(ADDR_FCI + 0x48)
#define FCI_HK0_DATA06D_REG						_APB_MEM32(ADDR_FCI + 0x4C)
#define FCI_HK0_DATA08S_REG						_APB_MEM32(ADDR_FCI + 0x50)
#define FCI_HK0_DATA09S_REG						_APB_MEM32(ADDR_FCI + 0x54)
#define FCI_HK0_DATA10S_REG						_APB_MEM32(ADDR_FCI + 0x58)
#define FCI_HK0_DATA11S_REG						_APB_MEM32(ADDR_FCI + 0x5C)
#define FCI_HK1_DATA0_REG						_APB_MEM32(ADDR_FCI + 0x60)
#define FCI_HK1_DATA1_REG						_APB_MEM32(ADDR_FCI + 0x64)
#define FCI_HK1_DATA2_REG						_APB_MEM32(ADDR_FCI + 0x68)
#define FCI_HK1_DATA3_REG						_APB_MEM32(ADDR_FCI + 0x6C)
#define FCI_HK1_DATA4_REG						_APB_MEM32(ADDR_FCI + 0x70)
#define FCI_HK1_DATA5_REG						_APB_MEM32(ADDR_FCI + 0x74)
#define FCI_HK1_DATA6_REG						_APB_MEM32(ADDR_FCI + 0x78)
#define FCI_HK1_DATA7_REG						_APB_MEM32(ADDR_FCI + 0x7C)
#define FCI_SPI_STATUS_REG						_APB_MEM32(ADDR_FCI + 0x80)
#define FCI_CCD_SCRIPT_REG						_APB_MEM32(ADDR_FCI + 0x84)
#define FCI_READBACK_REG						_APB_MEM32(ADDR_FCI + 0x88)
#define FCI_TRIGGER_REG							_APB_MEM32(ADDR_FCI + 0xCC)
#define FCI_VERSION_REG							_APB_MEM32(ADDR_FCI + 0xFC)


#define FDI_CONTROL_REG							_APB_MEM32(ADDR_FDI + 0x00)
#define FDI_STATUS_REG							_APB_MEM32(ADDR_FDI + 0x04)
#define FDI_DMA_ADDRESS_REG						_APB_MEM32(ADDR_FDI + 0x08)
#define FDI_DMA_SIZE_REG						_APB_MEM32(ADDR_FDI + 0x0C)
#define FDI_DMA_LIMIT_REG						_APB_MEM32(ADDR_FDI + 0x10)
#define FDI_DEBUG_SPI_REG						_APB_MEM32(ADDR_FDI + 0x20)
#define FDI_DEBUG_FIFO_REG						_APB_MEM32(ADDR_FDI + 0x24)
#define FDI_VERSION_REG							_APB_MEM32(ADDR_FDI + 0xFC)

/************************************* DMA Control *********************************************/
#define DMA_CONTROL_REG							_APB_MEM32(ADDR_DMA + 0x00)
#define DMA_STATUS_REG							_APB_MEM32(ADDR_DMA + 0x04)
#define DMA_LINE_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x08)
#define DMA_REQ0_SRC_REG						_APB_MEM32(ADDR_DMA + 0x40)
#define DMA_REQ0_DEST_REG						_APB_MEM32(ADDR_DMA + 0x44)
#define DMA_REQ0_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x48)
#define DMA_REQ0_CRC_REG						_APB_MEM32(ADDR_DMA + 0x4C)
#define DMA_REQ1_SRC_REG						_APB_MEM32(ADDR_DMA + 0x50)
#define DMA_REQ1_DEST_REG						_APB_MEM32(ADDR_DMA + 0x54)
#define DMA_REQ1_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x58)
#define DMA_REQ1_CRC_REG						_APB_MEM32(ADDR_DMA + 0x5C)
#define DMA_REQ2_SRC_REG						_APB_MEM32(ADDR_DMA + 0x60)
#define DMA_REQ2_DEST_REG						_APB_MEM32(ADDR_DMA + 0x64)
#define DMA_REQ2_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x68)
#define DMA_REQ2_CRC_REG						_APB_MEM32(ADDR_DMA + 0x6C)
#define DMA_REQ3_SRC_REG						_APB_MEM32(ADDR_DMA + 0x70)
#define DMA_REQ3_DEST_REG						_APB_MEM32(ADDR_DMA + 0x74)
#define DMA_REQ3_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x78)
#define DMA_REQ3_CRC_REG						_APB_MEM32(ADDR_DMA + 0x7C)
#define DMA_REQ4_SRC_REG						_APB_MEM32(ADDR_DMA + 0x80)
#define DMA_REQ4_DEST_REG						_APB_MEM32(ADDR_DMA + 0x84)
#define DMA_REQ4_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x88)
#define DMA_REQ4_CRC_REG						_APB_MEM32(ADDR_DMA + 0x8C)
#define DMA_REQ5_SRC_REG						_APB_MEM32(ADDR_DMA + 0x90)
#define DMA_REQ5_DEST_REG						_APB_MEM32(ADDR_DMA + 0x94)
#define DMA_REQ5_SIZE_REG						_APB_MEM32(ADDR_DMA + 0x98)
#define DMA_REQ5_CRC_REG						_APB_MEM32(ADDR_DMA + 0x9C)
#define DMA_REQ6_SRC_REG						_APB_MEM32(ADDR_DMA + 0xA0)
#define DMA_REQ6_DEST_REG						_APB_MEM32(ADDR_DMA + 0xA4)
#define DMA_REQ6_SIZE_REG						_APB_MEM32(ADDR_DMA + 0xA8)
#define DMA_REQ6_CRC_REG						_APB_MEM32(ADDR_DMA + 0xAC)
#define DMA_REQ7_SRC_REG						_APB_MEM32(ADDR_DMA + 0xB0)
#define DMA_REQ7_DEST_REG						_APB_MEM32(ADDR_DMA + 0xB4)
#define DMA_REQ7_SIZE_REG						_APB_MEM32(ADDR_DMA + 0xB8)
#define DMA_REQ7_CRC_REG						_APB_MEM32(ADDR_DMA + 0xBC)
#define DMA_VERSION_REG							_APB_MEM32(ADDR_DMA + 0xFC)

#define DMA_REQx_SRC_REG(x)						_APB_MEM32(ADDR_DMA + 0x40 + (x*0x10))
#define DMA_REQx_DEST_REG(x)					_APB_MEM32(ADDR_DMA + 0x44 + (x*0x10))
#define DMA_REQx_SIZE_REG(x)					_APB_MEM32(ADDR_DMA + 0x48 + (x*0x10))
#define DMA_REQx_CRC_REG(x)						_APB_MEM32(ADDR_DMA + 0x4C + (x*0x10))

#endif

