/************************************************************************************************

	Project:			CHEOPS On-Board Software
	Target System:		Leon3-Processor
	Language:			C

	Author:				B.Ulmer(IBU)
	Label:

	Header Information automatically generated by Subversion

	$Rev: 2134 $
	$Author: ulmer $
	$Date: 2017-06-01 18:20:48 +0200 (Do, 01 Jun 2017) $
	$Id: address.h 2134 2017-06-01 16:20:48Z ulmer $
	$HeadURL: https://svn.dlr.de/CHEOPS/03-SES_ENGINEERING/07-Software/Development/APS/trunk/src/Include/address.h $

*************************************************************************************************/
 
#ifndef __ADDRESS_H_
#define __ADDRESS_H_

#define AHB_ADDR_SDRAM			0x40000000			/* SDRAM */
#define AHB_SDRAM_SIZE			0x04000000			/*  64MB */

#define AHB_ADDR_APBCTRL		0x80000000			/* APB Bridge */
#define AHB_ADDR_APBCTRL_HIGH	0x80100000			/* APB Bridge */
#define AHB_APBCTRL_SIZE		0x00100000

#define AHB_ADDR_DSU			0x90000000
#define AHB_ADDR_DSU_SIZE		0x10000000

													/* APB */
#define ADDR_MCTRL				0x0000
#define ADDR_APBUART			0x0100
#define ADDR_IRQMP				0x0200
#define ADDR_GPTIMER			0x0300
#define ADDR_AHBUART_DBG		0x0700
#define ADDR_GRSPW				0x0A00
#define ADDR_FTAHBRAM			0x0E00
#define ADDR_ETHERNET			0x0F00

#endif
